name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - '**'
  
  workflow_dispatch:

jobs:
  CI-Jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup project
        run: make setup

      - name: Verify dependencies
        run: go mod verify
      
      - name: Run tests
        run: make tests

      - name: Run build
        run: make build

